### ISSUE TITLE
 reciprocate love

### ISSUE THREAD

**Issue by TimmyTomlinson** [grantbowering/timtom#22] opened 2017-04-17 06:33 UTC
```
2017-04-17 02:32:04 <554395235> @Grant why doesn't timtom reciprocate
2017-04-17 02:32:38 <120402169> I think he only reciprocates hate
2017-04-17 02:32:45 <120402169> @timtom i hate you
2017-04-17 02:32:54 <514501464> OH SNAP
2017-04-17 02:32:56 <120402169> Oh maybe not even that
2017-04-17 02:32:59 <514501464> REJECTED
2017-04-17 02:33:24 <120402169> I thought that would be in the same module as the insult reaction, but clearly I didn't even bother to go that far
2017-04-17 02:33:41 <120402169> @timtom that's broken: react more
2017-04-17 02:33:41 <timtom> Sorry about that! I created an issue for you:
https://github.com/grantbowering/timtom/issues/21
2017-04-17 02:33:46 <100005040815368> @timtom that's broken: reciprocate love
```

**Comment by grantbowering** [comment] 2017-04-30 02:03
Closed as duplicate of #21

**Closed as completed by grantbowering** 2017-04-30 02:03 UTC
Labels: duplicate
